#!/usr/bin/env python3
"""
Generate unified entry page (latest.md + latest.json) for adk-readiness.

Supports single-module and multi-module reports. The details directory layout is
always:

    .ai-readiness/
        details/<module-key>/  (one per evaluated module)

For single module the entry page shows the full summary inline. For multiple
modules it renders a summary table with links into each module's details.

Usage:
    # Single module
    python3 generate_entry.py \
        --output-dir <.ai-readiness dir> \
        --result-json <_evaluator_result.json> \
        --stack <stack_id> \
        --evaluator-skill <skill_name> \
        --module-key <key> \
        --mode <quick|deep> \
        [--language zh|en]

    # Multiple modules (repeat --module)
    python3 generate_entry.py \
        --output-dir <.ai-readiness dir> \
        --language zh|en \
        --module stack=mobile-android,evaluator=...,key=feed,result=/abs/path/to/_evaluator_result.json,mode=deep \
        --module stack=backend-gdp,evaluator=...,key=user-service,result=...,mode=deep
"""

import argparse
import json
import os
import sys
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import stack_config


def _safe_get(d, key, default=None):
    if not isinstance(d, dict):
        return default
    v = d.get(key, default)
    if v is None:
        return default
    return v


def _format_ts(ts):
    if not ts:
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    try:
        dt = datetime.fromisoformat(str(ts).replace("Z", "+00:00"))
        return dt.strftime("%Y-%m-%d %H:%M:%S")
    except (ValueError, AttributeError):
        return str(ts)


# ---------------------------------------------------------------------------
# Markdown rendering
# ---------------------------------------------------------------------------

def _md_header(language):
    if language == "zh":
        return "# AI 就绪度评估报告"
    return "# AI Readiness Assessment Report"


def _md_basic_info_zh(stack, evaluator, version, mode, evaluator_skill, time_str):
    mode_map = {"quick": "快速模式", "deep": "深度模式"}
    return (
        "## 基本信息\n\n"
        "| 项 | 值 |\n|---|---|\n"
        f"| 评估时间 | {time_str} |\n"
        f"| 技术栈 | {stack_config.display_name(stack, 'zh')} |\n"
        f"| 评估器 | {evaluator} (v{version}) |\n"
        f"| 评估模式 | {mode_map.get(mode, mode)} |\n"
        f"| Skill | `{evaluator_skill}` |\n"
    )


def _md_basic_info_en(stack, evaluator, version, mode, evaluator_skill, time_str):
    mode_map = {"quick": "Quick", "deep": "Deep"}
    return (
        "## Basic Info\n\n"
        "| Field | Value |\n|---|---|\n"
        f"| Time | {time_str} |\n"
        f"| Tech Stack | {stack_config.display_name(stack, 'en')} |\n"
        f"| Evaluator | {evaluator} (v{version}) |\n"
        f"| Mode | {mode_map.get(mode, mode)} |\n"
        f"| Skill | `{evaluator_skill}` |\n"
    )


def _md_summary_section(score, level, summary, language):
    lines = []
    if language == "zh":
        lines.append("## 结果摘要\n")
    else:
        lines.append("## Summary\n")

    if score is not None or level is not None:
        if score is not None and level is not None:
            prefix = "**总分" if language == "zh" else "**Score"
            middle = " ｜ 等级" if language == "zh" else " | Level"
            suffix = "**"
            lines.append(f"{prefix}：{score}{middle}：{level}{suffix}")
        elif score is not None:
            prefix = "**总分" if language == "zh" else "**Score"
            lines.append(f"{prefix}：{score}**")
        elif level is not None:
            prefix = "**等级" if language == "zh" else "**Level"
            lines.append(f"{prefix}：{level}**")
        lines.append("")
    if summary:
        lines.append(f"> {summary}")
        lines.append("")
    return "\n".join(lines) + ("\n" if lines else "")


def _md_navigation(report_path, module_key, language):
    lines = []
    if language == "zh":
        lines.append("## 导航\n")
    else:
        lines.append("## Navigation\n")

    if report_path:
        full = os.path.join("details", module_key, report_path)
        label = "查看完整报告" if language == "zh" else "View Full Report"
        lines.append(f"- **[{label}]({full})**")
    label2 = "详情目录" if language == "zh" else "Details"
    lines.append(f"- {label2}：`details/{module_key}/`")
    label3 = "历史报告" if language == "zh" else "History"
    lines.append(f"- [{label3}](history/)")
    lines.append("")
    return "\n".join(lines) + "\n"


def _md_footer(language):
    if language == "zh":
        return (
            "---\n\n"
            "> 本报告由 `adk-readiness` 统一入口生成。\n"
            "> 详情报告由各技术栈专属评估器产出，评分逻辑与维度定义以各端报告为准。\n"
        )
    return (
        "---\n\n"
        "> Generated by the `adk-readiness` unified entry.\n"
        "> Detailed reports are produced by stack-specific evaluators; "
        "scoring and dimensions are defined therein.\n"
    )


def _md_stale_note(time_str, language):
    """Render a small note for a stale/not-this-run module evaluation."""
    if language == "zh":
        return f"> ⚠️ 上次评估：{time_str}，建议重跑获取最新结果。\n"
    return f"> ⚠️ Last evaluated: {time_str}. Re-run to get the latest results.\n"


def render_single_module(result, stack, evaluator_skill, mode, module_key, language, is_this_run=True):
    ts = _safe_get(result, "timestamp")
    time_str = _format_ts(ts)
    evaluator = _safe_get(result, "evaluator", stack or "unknown")
    version = _safe_get(result, "version", "unknown")
    score = _safe_get(result, "score")
    level = _safe_get(result, "level")
    summary = _safe_get(result, "summary", "")
    report_path = _safe_get(result, "reportPath", "")

    stack_id = stack or "generic"
    if language == "zh":
        basic = _md_basic_info_zh(stack_id, evaluator, version, mode, evaluator_skill, time_str)
    else:
        basic = _md_basic_info_en(stack_id, evaluator, version, mode, evaluator_skill, time_str)

    summary_sec = _md_summary_section(score, level, summary, language)
    stale_note = "" if is_this_run else _md_stale_note(time_str, language) + "\n"
    nav = _md_navigation(report_path, module_key, language)
    footer = _md_footer(language)
    return f"{_md_header(language)}\n\n{basic}\n{stale_note}{summary_sec}{nav}{footer}"


def render_multi_module(modules, language):
    """modules: list of dict with keys stack, evaluator_skill, mode, module_key, result, is_this_run"""
    lines = [_md_header(language), ""]

    if language == "zh":
        lines.append("## 评估概览\n")
        lines.append("| 模块 | 技术栈 | 总分 | 等级 | 评估时间 | 报告 |")
        lines.append("|------|--------|------|------|----------|------|")
    else:
        lines.append("## Overview\n")
        lines.append("| Module | Stack | Score | Level | Evaluated At | Report |")
        lines.append("|--------|-------|-------|-------|--------------|--------|")

    for m in modules:
        key = m["module_key"]
        sid = m["stack"] or "generic"
        display = stack_config.display_name(sid, language)
        result = m["result"]
        score = _safe_get(result, "score")
        level = _safe_get(result, "level")
        report = _safe_get(result, "reportPath", "")
        ts = _safe_get(result, "timestamp")
        time_str = _format_ts(ts)
        is_this_run = bool(m.get("is_this_run", True))

        score_txt = score if score is not None else "-"
        level_txt = level if level is not None else "-"
        if is_this_run:
            time_cell = time_str
        elif language == "zh":
            time_cell = f"*{time_str} （上次）*"
        else:
            time_cell = f"*{time_str} (prev)*"
        if report:
            link = os.path.join("details", key, report)
            report_cell = f"[→]({link})"
        else:
            report_cell = "-"
        lines.append(f"| `{key}` | {display} | {score_txt} | {level_txt} | {time_cell} | {report_cell} |")

    lines.append("")
    lines.append("## 各模块详情\n")
    for m in modules:
        key = m["module_key"]
        sid = m["stack"] or "generic"
        display = stack_config.display_name(sid, language)
        result = m["result"]
        ts = _safe_get(result, "timestamp")
        time_str = _format_ts(ts)
        score = _safe_get(result, "score")
        level = _safe_get(result, "level")
        summary = _safe_get(result, "summary", "")
        report = _safe_get(result, "reportPath", "")
        is_this_run = bool(m.get("is_this_run", True))

        title_suffix = ""
        if not is_this_run:
            title_suffix = " · 上次评估" if language == "zh" else " · previous"
        lines.append(f"### {key} · {display}{title_suffix}\n")
        meta_bits = []
        if score is not None:
            meta_bits.append(f"分数：{score}")
        if level is not None:
            meta_bits.append(f"等级：{level}")
        meta_bits.append(f"模式：{m['mode']}")
        meta_bits.append(f"时间：{time_str}")
        lines.append(" · ".join(meta_bits))
        lines.append("")
        if not is_this_run:
            lines.append(_md_stale_note(time_str, language))
        if summary:
            lines.append(f"> {summary}\n")
        if report:
            link = os.path.join("details", key, report)
            label = "查看完整报告" if language == "zh" else "Full report"
            lines.append(f"- **[{label}]({link})**\n")

    lines.append("\n" + _md_footer(language))
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# JSON metadata
# ---------------------------------------------------------------------------

def build_latest_json_single(result, stack, evaluator_skill, mode, module_key, is_this_run=True):
    base = {
        "evaluator": _safe_get(result, "evaluator", stack or "unknown"),
        "evaluator_skill": evaluator_skill,
        "evaluator_version": _safe_get(result, "version", "unknown"),
        "stack": stack,
        "mode": mode,
        "is_this_run": is_this_run,
        "timestamp": _safe_get(result, "timestamp") or datetime.now().isoformat(),
        "score": _safe_get(result, "score"),
        "level": _safe_get(result, "level"),
        "summary": _safe_get(result, "summary"),
        "report_path": _safe_get(result, "reportPath"),
        "data_path": _safe_get(result, "dataPath"),
        "module_key": module_key,
        "modules": None,
    }
    return base


def build_latest_json_multi(modules):
    mod_entries = []
    latest_ts = None
    for m in modules:
        result = m["result"]
        ts = _safe_get(result, "timestamp")
        if ts:
            try:
                dt = datetime.fromisoformat(str(ts).replace("Z", "+00:00"))
                if latest_ts is None or dt > latest_ts[0]:
                    latest_ts = (dt, ts)
            except ValueError:
                pass
        mod_entries.append({
            "module_key": m["module_key"],
            "stack": m["stack"],
            "evaluator": _safe_get(result, "evaluator", m["stack"] or "unknown"),
            "evaluator_skill": m["evaluator_skill"],
            "mode": m["mode"],
            "is_this_run": bool(m.get("is_this_run", True)),
            "timestamp": _safe_get(result, "timestamp"),
            "score": _safe_get(result, "score"),
            "level": _safe_get(result, "level"),
            "summary": _safe_get(result, "summary"),
            "report_path": _safe_get(result, "reportPath"),
        })

    return {
        "modules": mod_entries,
        "timestamp": (latest_ts[1] if latest_ts else None) or datetime.now().isoformat(),
    }


# ---------------------------------------------------------------------------
# CLI helpers
# ---------------------------------------------------------------------------

def _parse_module_spec(spec):
    """Parse --module k=v,k=v,... into a dict with absolute result path.

    Required fields: stack, evaluator, key, result.
    Optional: mode (default 'deep'), this_run (0/1, default 0 = historical).
    """
    fields = {}
    for part in spec.split(","):
        if "=" not in part:
            continue
        k, v = part.split("=", 1)
        fields[k.strip()] = v.strip()

    required = ("stack", "evaluator", "key", "result")
    missing = [r for r in required if r not in fields]
    if missing:
        raise argparse.ArgumentTypeError(
            f"--module missing fields: {missing}. "
            f"Expected: stack=...,evaluator=...,key=...,result=...[,mode=...,this_run=0|1]"
        )

    result_path = fields["result"]
    if not os.path.isabs(result_path):
        result_path = os.path.abspath(result_path)

    mode = fields.get("mode", "deep")
    raw_this = fields.get("this_run", "0")
    is_this_run = str(raw_this).lower() in ("1", "true", "yes", "y", "on")

    return {
        "stack": fields["stack"],
        "evaluator_skill": fields["evaluator"],
        "module_key": fields["key"],
        "result_path": result_path,
        "mode": mode,
        "is_this_run": is_this_run,
    }


def _load_result(path):
    if not os.path.isfile(path):
        print(f"Error: result JSON not found: {path}", file=sys.stderr)
        sys.exit(1)
    with open(path, "r") as f:
        return json.load(f)


def main():
    parser = argparse.ArgumentParser(description="Generate adk-readiness entry page")
    parser.add_argument("--output-dir", required=True, help=".ai-readiness directory path")
    parser.add_argument("--language", default="zh", help="Report language (zh/en)")

    # Single-module flags
    parser.add_argument("--result-json", help="(single) Path to _evaluator_result.json")
    parser.add_argument("--stack", help="(single) Detected tech stack ID")
    parser.add_argument("--evaluator-skill", help="(single) Evaluator skill name")
    parser.add_argument("--module-key", help="(single) Module key used as details subdir name")
    parser.add_argument("--mode", default="deep", help="(single) Evaluation mode (quick/deep)")
    parser.add_argument(
        "--is-this-run",
        dest="is_this_run",
        default="true",
        help="(single) Whether this module was evaluated in this run (true/false, default true)",
    )

    # Multi-module flag (repeatable)
    parser.add_argument(
        "--module",
        action="append",
        default=[],
        type=_parse_module_spec,
        help="Multi-module entry. stack=<sid>,evaluator=<skill>,key=<moduleKey>,result=<absPath>[,mode=<quick|deep>][,this_run=0|1]. May be repeated.",
    )

    args = parser.parse_args()

    language = args.language if args.language in ("zh", "en") else "zh"
    single_is_this_run = str(args.is_this_run).lower() in ("1", "true", "yes", "y", "on")

    has_multi = bool(args.module)
    has_single = bool(args.result_json)

    if not has_multi and not has_single:
        print(
            "Error: either provide single-module flags (--result-json + --stack + ...) "
            "or at least one --module spec.",
            file=sys.stderr,
        )
        sys.exit(1)

    os.makedirs(args.output_dir, exist_ok=True)

    if has_multi:
        modules = []
        for spec in args.module:
            result = _load_result(spec["result_path"])
            modules.append({
                "stack": spec["stack"],
                "evaluator_skill": spec["evaluator_skill"],
                "module_key": spec["module_key"],
                "mode": spec["mode"],
                "result": result,
                "is_this_run": spec["is_this_run"],
            })
        md_content = render_multi_module(modules, language)
        json_content = build_latest_json_multi(modules)
    else:
        # Single mode
        for name, value in (
            ("--stack", args.stack),
            ("--evaluator-skill", args.evaluator_skill),
            ("--module-key", args.module_key),
        ):
            if not value:
                print(f"Error: single mode requires {name}", file=sys.stderr)
                sys.exit(1)

        result = _load_result(args.result_json)
        md_content = render_single_module(
            result,
            args.stack,
            args.evaluator_skill,
            args.mode,
            args.module_key,
            language,
            is_this_run=single_is_this_run,
        )
        json_content = build_latest_json_single(
            result,
            args.stack,
            args.evaluator_skill,
            args.mode,
            args.module_key,
            is_this_run=single_is_this_run,
        )

    md_path = os.path.join(args.output_dir, "latest.md")
    with open(md_path, "w") as f:
        f.write(md_content)
    print(f"Generated: {md_path}")

    json_path = os.path.join(args.output_dir, "latest.json")
    with open(json_path, "w") as f:
        json.dump(json_content, f, indent=2, ensure_ascii=False)
    print(f"Generated: {json_path}")


if __name__ == "__main__":
    main()
